
BLOCK-LEVEL ON ERROR UNDO, THROW.

MESSAGE "Before":U
	VIEW-AS ALERT-BOX.
&IF TRUE &THEN
    MESSAGE "TRUE":U VIEW-AS ALERT-BOX.
&ELSEIF FALSE &THEN
    MESSAGE "FALSE":U VIEW-AS ALERT-BOX.
&ELSE
	MESSAGE "MAYBE":U VIEW-AS ALERT-BOX.    
&ENDIF
MESSAGE "After":U
	VIEW-AS ALERT-BOX.