
BLOCK-LEVEL ON ERROR UNDO, THROW.

MESSAGE "Some stuff before"
VIEW-AS ALERT-BOX.

&IF (TRUE) &THEN

    &IF (TRUE) &THEN
        MESSAGE "DO THIS"
        VIEW-AS ALERT-BOX.
    &ELSE
        MESSAGE "DON'T DO THIS"
        VIEW-AS ALERT-BOX.
    &ENDIF

&ELSEIF (FALSE) &THEN

    MESSAGE "NOT THIS"
    VIEW-AS ALERT-BOX.

&ELSE

    MESSAGE "NOT THIS EITHER"
    VIEW-AS ALERT-BOX.

&ENDIF

MESSAGE "some stuff after"
VIEW-AS ALERT-BOX.